<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ManageFood.aspx.cs" Inherits="Food_Order.ManageFood" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <center>
    <div class="">
        
        <h1>Manage Food</h1>

        <asp:DropDownList ID="DropDownList1" runat="server"> 
            <asp:ListItem>Select Food Type </asp:ListItem>
            <asp:ListItem>Veg</asp:ListItem>
            <asp:ListItem>Non Veg</asp:ListItem>
            <asp:ListItem>Beverages</asp:ListItem>
        </asp:DropDownList><br /><br />

        <asp:TextBox ID="TextBox1" runat="server" reqired="" placeholder="Enter Food Name"></asp:TextBox><br />
        <asp:TextBox ID="TextBox2" runat="server" type="number" reqired="" placeholder="Enter Food Price"></asp:TextBox><br />
        <asp:TextBox ID="TextBox3" runat="server" reqired="" placeholder="Enter Food Description"></asp:TextBox><br />
        <asp:FileUpload ID="FileUpload1" runat="server" /><br /><br />
        <asp:Button ID="Button1" runat="server" Text="Add" OnClick="Button1_Click" /><br /><br /><br />
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <br /><br />
    </div>
        <hr />

    <div class="">
        <h1>Manage Foods</h1>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="foodtype" HeaderText="foodtype" SortExpression="foodtype" />
                <asp:BoundField DataField="foodname" HeaderText="foodname" SortExpression="foodname" />
                <asp:BoundField DataField="foodprice" HeaderText="foodprice" SortExpression="foodprice" />
                <asp:BoundField DataField="fooddes" HeaderText="fooddes" SortExpression="fooddes" />
                <asp:BoundField DataField="img" HeaderText="img" SortExpression="img" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [foods]" DeleteCommand="DELETE FROM [foods] where [Id]=@Id" UpdateCommand="UPDATE foods set foodtype=@foodtype , foodname=@foodname , foodprice=@foodprice , fooddes=@fooddes where [Id]=@Id"></asp:SqlDataSource>
        <br />
    </div>
    </center>

</asp:Content>
